// src/pages/premierLeagueTable.js

export const premierLeagueTable = [
  {
    position: 1,
    team: "Liverpool 🏆",
    played: 37,
    wins: 25,
    draws: 8,
    losses: 4,
    goalsFor: 85,
    goalsAgainst: 40,
    goalDifference: 45,
    points: 83,
    note: "Champions League",
  },
  {
    position: 2,
    team: "Arsenal",
    played: 37,
    wins: 19,
    draws: 14,
    losses: 4,
    goalsFor: 67,
    goalsAgainst: 33,
    goalDifference: 34,
    points: 71,
    note: "Champions League",
  },
  {
    position: 3,
    team: "Manchester City",
    played: 37,
    wins: 20,
    draws: 8,
    losses: 9,
    goalsFor: 70,
    goalsAgainst: 44,
    goalDifference: 26,
    points: 68,
    note: "Champions League",
  },
  {
    position: 4,
    team: "Newcastle United",
    played: 37,
    wins: 20,
    draws: 6,
    losses: 11,
    goalsFor: 68,
    goalsAgainst: 46,
    goalDifference: 22,
    points: 66,
    note: "Champions League",
  },
  {
    position: 5,
    team: "Chelsea",
    played: 37,
    wins: 19,
    draws: 9,
    losses: 9,
    goalsFor: 63,
    goalsAgainst: 43,
    goalDifference: 20,
    points: 66,
    note: "Champions League",
  },
  {
    position: 6,
    team: "Aston Villa",
    played: 37,
    wins: 19,
    draws: 9,
    losses: 9,
    goalsFor: 58,
    goalsAgainst: 49,
    goalDifference: 9,
    points: 66,
    note: "Europa League",
  },
  {
    position: 7,
    team: "Nottingham Forest",
    played: 37,
    wins: 19,
    draws: 8,
    losses: 10,
    goalsFor: 58,
    goalsAgainst: 45,
    goalDifference: 13,
    points: 65,
    note: "Conference League",
  },
  {
    position: 8,
    team: "Brighton & Hove Albion",
    played: 37,
    wins: 15,
    draws: 13,
    losses: 9,
    goalsFor: 62,
    goalsAgainst: 58,
    goalDifference: 4,
    points: 58,
  },
  {
    position: 9,
    team: "Brentford",
    played: 37,
    wins: 16,
    draws: 7,
    losses: 14,
    goalsFor: 65,
    goalsAgainst: 56,
    goalDifference: 9,
    points: 55,
  },
  {
    position: 10,
    team: "Fulham",
    played: 37,
    wins: 15,
    draws: 9,
    losses: 13,
    goalsFor: 54,
    goalsAgainst: 52,
    goalDifference: 2,
    points: 54,
  },
  {
    position: 11,
    team: "Bournemouth",
    played: 37,
    wins: 14,
    draws: 11,
    losses: 12,
    goalsFor: 56,
    goalsAgainst: 46,
    goalDifference: 10,
    points: 53,
  },
  {
    position: 12,
    team: "Crystal Palace",
    played: 37,
    wins: 13,
    draws: 13,
    losses: 11,
    goalsFor: 50,
    goalsAgainst: 50,
    goalDifference: 0,
    points: 52,
    note: "Europa League",
  },
  {
    position: 13,
    team: "Everton",
    played: 37,
    wins: 10,
    draws: 15,
    losses: 12,
    goalsFor: 41,
    goalsAgainst: 44,
    goalDifference: -3,
    points: 45,
  },
  {
    position: 14,
    team: "Wolverhampton Wanderers",
    played: 37,
    wins: 12,
    draws: 5,
    losses: 20,
    goalsFor: 53,
    goalsAgainst: 68,
    goalDifference: -15,
    points: 41,
  },
  {
    position: 15,
    team: "West Ham United",
    played: 37,
    wins: 10,
    draws: 10,
    losses: 17,
    goalsFor: 43,
    goalsAgainst: 61,
    goalDifference: -18,
    points: 40,
  },
  {
    position: 16,
    team: "Manchester United",
    played: 37,
    wins: 10,
    draws: 9,
    losses: 18,
    goalsFor: 42,
    goalsAgainst: 54,
    goalDifference: -12,
    points: 39,
  },
  {
    position: 17,
    team: "Tottenham Hotspur",
    played: 37,
    wins: 11,
    draws: 5,
    losses: 21,
    goalsFor: 63,
    goalsAgainst: 61,
    goalDifference: 2,
    points: 38,
    note: "Champions League",
  },
  {
    position: 18,
    team: "Leicester City",
    played: 37,
    wins: 6,
    draws: 7,
    losses: 24,
    goalsFor: 33,
    goalsAgainst: 78,
    goalDifference: -45,
    points: 25,
    note: "Relegated",
  },
  {
    position: 19,
    team: "Ipswich Town",
    played: 37,
    wins: 4,
    draws: 10,
    losses: 23,
    goalsFor: 35,
    goalsAgainst: 79,
    goalDifference: -44,
    points: 22,
    note: "Relegated",
  },
  {
    position: 20,
    team: "Southampton",
    played: 37,
    wins: 2,
    draws: 6,
    losses: 29,
    goalsFor: 25,
    goalsAgainst: 84,
    goalDifference: -59,
    points: 12,
    note: "Relegated",
  },
];
